import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import joblib
import os

# Make sure 'models' directory exists
os.makedirs("models", exist_ok=True)

### ========== SPAM DETECTOR TRAINING ==========

normal_descriptions = [
    "Robbery reported at local bank",
    "Fire broke out in apartment building",
    "Suspicious person loitering outside the school",
    "Armed individual seen near shopping mall",
    "Attempted car theft in parking lot",
    "Multiple gunshots heard in downtown area",
    "Street fight between two individuals",
    "Explosion heard near railway station",
    "Gas leak detected in the neighborhood",
    "House burglary while owners were away",
    "Missing child reported in city park",
    "Stabbing incident near metro station",
    "Loud noise reported near industrial zone",
    "Motorcycle crash on highway",
    "Traffic accident involving three vehicles",
    "Break-in reported at electronics store",
    "Armed robbery at gas station",
    "Man found unconscious on sidewalk",
    "Woman attacked while jogging",
    "Hit and run reported near school"
    "Bank mein dakaiti ki koshish hui",
"School ke bahar mashkook shakhs dekha gaya",
"Apartment mein aag lag gayi",
"Shopping mall ke paas musallah shakhs dekha gaya",
"Parking mein car chori ka waqia hua",
"Downtown mein goliyon ki awaz sunayi di",
"Do afraad ke darmiyan street fight hui",
"Railway station ke paas dhamaka hua",
"Colony mein gas leak hua",
"Makaan mein chori jab malik ghar par nahi tha",
"Bachay ke gum hone ki report mili",
"Metro station ke kareeb chaku zani ka waqia",
"Industrial area mein shore sunayi diya",
"Highway par motorcycle ka accident hua",
"Teen gaariyon ka traffic accident hua",
"Electronics shop mein chori ki koshish",
"Petrol pump par musallah dakaiti hui",
"Footpath par behosh shakhs mila",
"Jogging karte waqt aurat par hamla hua",
"School ke paas hit and run case hua",
"Nadi ke qareeb lash mili",
"Masjid ke bahar jhagda hua",
"Park mein ajnabi shakhs bachon se baat kar raha tha",
"Bridge ke neeche fire brigade bulayi gayi",
"Police ne ek chori shuda gaari baramad ki",
"Hospital ke samne danga hua",
"Cycle chori hone ki report file hui",
"Public transport mein musafir ka mobile chori hua",
"Ghar mein dakhil hone ki koshish hui",
"Jamaat ke doran fire alarm chala",
"Train station ke qareeb ajnabi bag mila",
"Bus stand par afraad ka jhagda hua",
"ATM par shakhs ne forcefully paise nikalwaye",
"Warehouse mein aag lag gayi",
"School ke andar security breach hua",
"Road par andheray mein shakhs mashkook laga",
"Car accident ke baad fire lagi",
"Mobile snatching ki koshish hui",
"Motorbike par do afraad ne wallet cheena",
"Market mein chor pakra gaya",
"Gas cylinder phat gaya",
"Chhat se kisi ne pathar phenka",
"Lift mein shakhs ne aurat ko tang kiya",
"Hospital mein patient ka saman chori hua",
"Bakra mandi se janwar chori hua",
"Highway par truck ka accident hua",
"Hostel ke andar chori ki report",
"Building mein elevator mein phans gaye log",
"Garage mein daka pada",
"Train mein musafir se saman cheena gaya",
"Thana mein FIR darj karwayi gayi",

] * 10  # Replicating to get 200 real

spam_descriptions = [

       "Congratulations! You have won a brand new car!",
        "Urgent: Verify your identity to avoid suspension",
        "Claim your free hotel stay now!",
        "Limited time offer! Act fast to win rewards",
        "Click this link for a secret cash bonus",
        "You have unclaimed crypto in your wallet",
        "Your social media account has been compromised",
        "Confirm your password to secure your account",
        "Get access to premium channels for free",
        "Your number is selected for lucky draw",
        "Join this survey and get paid instantly",
        "Your loan has been pre-approved, click here",
        "Unlock your free internet package now",
        "Get 5 lakh rupees by filling this form",
        "You're eligible for free education grant",
        "Hot deals only for today, check now",
        "Claim your pension fund by verifying ID",
        "Hurry! Free shopping voucher inside",
        "Apka account block hone wala hai",
        "Free recharge jeetne ka moka chhodiye mat",
        "Tumhara gift tayar hai, abhi claim karo",
        "Aaj ka lucky winner aap ho",
        "You have been selected for job placement",
        "Government scheme launched, apply free now",
        "Warning! Suspicious activity on your account",
        "Tumhara SIM 24 ghante mein block hoga",
        "Click kro aur free game credits lo",
        "Special discount coupon waiting for you",
        "Ghar baithe online paisa kamao",
        "Apna CNIC bhejo aur 20 hazar lo",
        "Your credit score just got updated",
        "Bitcoin scheme only for VIP members",
        "Download this app and earn every hour",
        "Check your eligibility for car loan",
        "Amazon reward claim karne ka last chance",
        "Get free medicine from government scheme",
        "Tumhara electric bill waive ho sakta hai",
        "Get your free iPhone case now",
        "Claim petrol subsidy abhi!",
        "Aapka number IPL draw mein jeeta hai",
        "Tumhara Gmail password expire hone wala hai",
        "Free concert tickets only for you",
        "Online form bharo aur 2 din mein paisa lo",
        "Join our telegram and get $10 free",
        "Abhi invest karo aur 3x return lo",
        "Your OTP is 456723 — don not share",
        "Limited stock left for this prize",
        "Instant approval for your housing loan",
        "You have received a foreign remittance",
        "Tumhara mobile hack hone wala hai",
        "Apne documents upload kro verification ke liye",
        "Claim your 1-year Netflix subscription",
        "Free laptop distribution started — apply now",
        "Aaj raat 12 baje tak valid offer",
        "Suspicious login detected from another location",
        "You are our 100th visitor, click now",
        "Tumhara Facebook password expire ho chuka hai",
        "Exclusive gift offer just for you",
        "Make money from Instagram today",
        "Apko bonus diya gaya hai wallet mein",
        "Only 2 minutes to win this phone",
        "Click kro aur sab kuch free milega",
        "Download karo aur free PUBG UC lo",
        "Medical test free sirf aaj",
        "Aap eligible hain Covid fund ke liye",
        "Zaroori notification: account verify karo",
        "Your bank details need to be updated",
        "Apne PAN card details abhi submit karein",
        "You have inherited Rs. 5 million!",
        "Tumhara SIM cloning detect hua hai",
        "Click here to save your contacts",
        "Share this with 10 friends to win",
        "1 saal ka free meal plan hasil karo",
        "Your Gmail is full, click to fix",
        "Join VIP scheme and earn weekly",
        "Congratulations, your Aadhaar is verified",
        "Urgent server maintenance alert",
        "Earn $100 per survey you fill",
        "Free car service available now",
        "Bank alert: immediate login required",
        "Tumhara reward ready hai claim ke liye",
        "Your digital KYC is pending",
        "Click for tax refund of Rs. 9000",
        "Tum VIP user ban chuke ho",
        "Unlock unlimited internet speed",
        "Tumhara cashback pending hai",
        "Aapka phone number lucky list mein hai",
        "Get free food coupons in seconds",
        "Register kro aur free shopping lo",
        "Fake traffic challan alert — click now",
        "Earn via scratch card spins daily",
        "This document is for your eyes only",
        "Tumhare naam ki lottery lag gayi hai",
        "Click here for your free air ticket",
        "Beware! Account access from unknown IP",
        "Apply for scholarship now — no fee",
        "Tumhara electricity bill refund hone wala hai",
        "Amazon prime user banne ka moka",
        "Online quiz jeeto aur paisa kamao",
        "Aapke liye ek surprise parcel hai",
        "Free 4G SIM activation offer",
        "Ghar baithe car insurance apply kro",
        "Click to activate WhatsApp premium pack",
        "Last warning: verify your details now",
        "You have been gifted an iPad — claim it",
"Aapke liye ek zaroori email hai",
"Your wallet is about to expire"

]* 10  # Replicating to get 200 spam

all_descriptions = normal_descriptions + spam_descriptions
labels = ["real"] * len(normal_descriptions) + ["spam"] * len(spam_descriptions)

df_spam = pd.DataFrame({
    "description": all_descriptions,
    "label": labels
})

spam_vectorizer = TfidfVectorizer()
X_spam = spam_vectorizer.fit_transform(df_spam["description"])
y_spam = df_spam["label"]

spam_model = MultinomialNB()
spam_model.fit(X_spam, y_spam)

# Save spam detection model and vectorizer
joblib.dump(spam_model, "models/spam_detector_model.pkl")
joblib.dump(spam_vectorizer, "models/spam_vectorizer.pkl")
print("✅ Spam detector trained and saved.")


### ========== INCIDENT TYPE CLASSIFIER ==========

incident_data = {
    "description": [
        "There was a robbery at the bank",
        "Fire broke out in the warehouse",
        "Suspicious person near the school",
        "Man with weapon spotted",
        "House burglary reported",
        "Accident on the highway",
        "Street fight reported",
        "Loud explosion heard nearby",
        "Suspicious activity near park",
        "Robbery at the convenience store",
        "Assault reported downtown",
        "Fire reported in apartment building",
        "Car accident at 5th Avenue",
        "Explosion in factory area",
        "Shots fired at shopping center",
        "Vandalism at public library",
        "Stabbing incident near market",
        "Armed robbery at gas station",
        "Domestic violence reported",
        "Fight broke out at bar",
        "Suspicious package at subway station",
        "Fire alarm at office complex",
        "Break-in at electronics shop",
        "Vehicle theft in parking lot",
        "Hit and run reported",
        "Kidnapping attempt in alley",
        "Drunk driving accident",
        "Harassment complaint at workplace",
        "Graffiti reported at school wall",
        "Molestation attempt in park",
        "Protest turned violent",
        "Man exposing himself in public",
        "Pickpocketing at bus terminal",
        "Chain snatching near ATM",
        "Gunfire heard near hospital",
        "Illegal drugs found in locker",
        "Trespassing in restricted area",
        "Explosion near power grid",
        "Burglary attempt failed",
        "Woman assaulted in taxi",
        "Knife attack at train station",
        "Burning car on roadside",
        "Child abduction alert",
        "Crowd violence at event",
        "Police chase through city",
        "Fake currency seized",
        "Stolen bike found",
        "Cyber crime report",
        "Gang violence in slum",
        "Fake news spreading on social media",
        "Burglars escaped through window",
        "Thieves caught red handed",
        "Security breach at hospital",
        "Fire at school lab",
        "Unauthorized protest on road",
        "Serial pickpocket arrested",
        "Attempted suicide on bridge",
        "Arson suspected in forest fire",
        "Murder investigation started",
        "Gun recovered from suspect",
        "Illegal weapons in basement",
        "Bribery case exposed",
        "Child trafficking racket busted",
        "Fake identity discovered",
        "Explosion near petrol pump",
        "Riot control police deployed",
        "Manhole explosion injures pedestrians",
        "Dangerous driving near park",
        "Firecracker factory explosion",
        "ATM tampering attempt",
        "Women harassment in bus",
        "Snatching mobile on street",
        "Smuggling attempt at airport",
        "Dead body found in river",
        "Bomb scare at courthouse",
        "Clashes between two groups",
        "Fake degrees recovered",
        "Man murdered in apartment",
        "Multiple stabbings at rally",
        "Shootout between gangs",
        "Fire destroyed textile mill",
        "Suspicious drone flying near embassy",
        "Cyberbullying complaint lodged",
        "Internet scam reported",
        "Underage driving accident",
        "Vehicle explosion downtown",
        "Attempted rape case filed",
        "Prisoner escaped from jail",
        "Gunshot heard near university",
        "Chemical leak in lab",
        "Fire at fuel depot",
        "Riot after sports event",
        "Man attempted to jump off bridge",
        "High-speed chase ends in crash",
        "False alarm of bomb",
        "Gas leak in building",
        "Masked men robbed jewelry shop",
        "Attempted murder charge filed",
        "Teenager caught with weapon",
        "Students fighting in school",
        "Corruption complaint filed",
        "Group assault on pedestrian",
        "Acid attack victim hospitalized",
        "Criminal gang busted by police",
        "Molestation in metro train",
        "Cash looted from delivery van"
    ],
    "type": [
        "robbery",
        "fire",
        "suspicious_activity",
        "armed_person",
        "burglary",
        "accident",
        "violence",
        "explosion",
        "suspicious_activity",
        "robbery",
        "assault",
        "fire",
        "accident",
        "explosion",
        "armed_person",
        "vandalism",
        "assault",
        "robbery",
        "domestic_violence",
        "violence",
        "suspicious_activity",
        "fire",
        "burglary",
        "theft",
        "accident",
        "kidnapping",
        "accident",
        "harassment",
        "vandalism",
        "molestation",
        "riot",
        "indecent_exposure",
        "theft",
        "snatching",
        "armed_person",
        "drugs",
        "trespassing",
        "explosion",
        "burglary",
        "assault",
        "armed_person",
        "fire",
        "kidnapping",
        "riot",
        "chase",
        "fraud",
        "theft",
        "cyber_crime",
        "gang_violence",
        "fake_news",
        "burglary",
        "robbery",
        "security_breach",
        "fire",
        "protest",
        "theft",
        "suicide_attempt",
        "arson",
        "murder",
        "armed_person",
        "illegal_weapons",
        "bribery",
        "child_trafficking",
        "fraud",
        "explosion",
        "riot",
        "explosion",
        "accident",
        "explosion",
        "atm_fraud",
        "harassment",
        "snatching",
        "smuggling",
        "murder",
        "bomb_threat",
        "violence",
        "fraud",
        "murder",
        "assault",
        "gang_violence",
        "fire",
        "suspicious_activity",
        "cyberbullying",
        "fraud",
        "accident",
        "explosion",
        "molestation",
        "escape",
        "armed_person",
        "chemical_leak",
        "fire",
        "riot",
        "suicide_attempt",
        "accident",
        "bomb_threat",
        "gas_leak",
        "robbery",
        "attempted_murder",
        "illegal_weapons",
        "violence",
        "corruption",
        "assault",
        "acid_attack",
        "gang_violence",
        "molestation",
        "robbery"
    ]
}


df_type = pd.DataFrame(incident_data)

incident_vectorizer = TfidfVectorizer()
X_type = incident_vectorizer.fit_transform(df_type["description"])
y_type = df_type["type"]

incident_model = MultinomialNB()
incident_model.fit(X_type, y_type)

# Save incident classifier model and vectorizer
joblib.dump(incident_model, "models/incident_classifier.pkl")
joblib.dump(incident_vectorizer, "models/vectorizer.pkl")
print("✅ Incident classifier trained and saved.")
